### ISSUE TITLE
执行出错

### ISSUE THREAD

**Issue by leiletter** [Mashiro2000/HeyTap#1]
执行浏览秒杀专区...
Traceback (most recent call last):
  File "HeyTap.py", line 635, in <module>
    heyTap.start()
  File "HeyTap.py", line 626, in start
    self.runTaskRewardList()                # 运行天天领现金
  File "HeyTap.py", line 457, in runTaskRewardList
    self.viewCashTask(each)
  File "HeyTap.py", line 610, in viewCashTask
    self.getCash(dic=dic,taskName=dic['taskName'],channel=3)
TypeError: getCash() got an unexpected keyword argument 'taskName'
请问是缺少什么模块嘛？

**Comment by Mashiro2000** [comment]
代码层面问题，已修正
